export const staffList = [
  {
    name: "Mr. John Okoye",
    department: "Science",
    subjects: ["Physics", "Mathematics"],
    experience: 15,
    waecPassRate: 89,
    bio: "John is a passionate educator with over 15 years in teaching science subjects and mentoring students for success.",
    cv: "/downloads/john-okoye-cv.pdf",
  },
  {
    name: "Mrs. Grace Umeh",
    department: "Arts",
    subjects: ["English", "Literature"],
    experience: 12,
    waecPassRate: 93,
    bio: "Grace has a deep love for the humanities and brings poetry and prose alive for her students.",
    cv: "/downloads/grace-umeh-cv.pdf",
  },
  {
    name: "Mr. Samuel Obi",
    department: "Commercial",
    subjects: ["Economics", "Commerce"],
    experience: 10,
    waecPassRate: 85,
    bio: "Samuel is a specialist in commerce-related subjects and has helped many students excel in national exams.",
    cv: "/downloads/samuel-obi-cv.pdf",
  },
  {
    name: "Mrs. Theresa Nnaji",
    department: "Science",
    subjects: ["Biology", "Chemistry"],
    experience: 13,
    waecPassRate: 91,
    bio: "Theresa brings biology to life and encourages critical thinking through real-world science applications.",
    cv: "/downloads/theresa-nnaji-cv.pdf",
  },
  {
    name: "Mr. David Eze",
    department: "Arts",
    subjects: ["Christian Religious Studies", "Civic Education"],
    experience: 9,
    waecPassRate: 88,
    bio: "David inspires students with values-based education rooted in moral development and social awareness.",
    cv: "/downloads/david-eze-cv.pdf",
  },
  {
    name: "Mrs. Linda Okafor",
    department: "Commercial",
    subjects: ["Accounting", "Business Studies"],
    experience: 14,
    waecPassRate: 90,
    bio: "Linda has over a decade of experience preparing students for success in finance and accounting.",
    cv: "/downloads/linda-okafor-cv.pdf",
  },
  {
    name: "Mr. Peter Anya",
    department: "Science",
    subjects: ["Further Mathematics", "Technical Drawing"],
    experience: 11,
    waecPassRate: 86,
    bio: "Peter specializes in technical and quantitative subjects, nurturing future engineers and architects.",
    cv: "/downloads/peter-anya-cv.pdf",
  },
  {
    name: "Miss Hannah Bassey",
    department: "Arts",
    subjects: ["French", "English"],
    experience: 8,
    waecPassRate: 92,
    bio: "Hannah introduces students to language through immersive, interactive techniques and cross-cultural exposure.",
    cv: "/downloads/hannah-bassey-cv.pdf",
  },
  {
    name: "Mr. Emmanuel Udo",
    department: "Commercial",
    subjects: ["Marketing", "Entrepreneurship"],
    experience: 7,
    waecPassRate: 84,
    bio: "Emmanuel brings modern business practices into the classroom, shaping future entrepreneurs.",
    cv: "/downloads/emmanuel-udo-cv.pdf",
  },
  {
    name: "Mrs. Rose Nwachukwu",
    department: "Science",
    subjects: ["Computer Studies", "ICT"],
    experience: 10,
    waecPassRate: 87,
    bio: "Rose introduces students to digital tools and coding, ensuring they stay ahead in tech.",
    cv: "/downloads/rose-nwachukwu-cv.pdf",
  },
  {
    name: "Mr. Felix Okon",
    department: "Arts",
    subjects: ["Government", "History"],
    experience: 12,
    waecPassRate: 89,
    bio: "Felix is a seasoned historian who fosters political awareness and critical thought in his classes.",
    cv: "/downloads/felix-okon-cv.pdf",
  },
  {
    name: "Mrs. Chioma Egwu",
    department: "Commercial",
    subjects: ["Office Practice", "Typewriting"],
    experience: 13,
    waecPassRate: 91,
    bio: "Chioma builds practical business admin skills, essential for both exams and real-world tasks.",
    cv: "/downloads/chioma-egwu-cv.pdf",
  },
  {
    name: "Mr. Jude Ibe",
    department: "Science",
    subjects: ["Agricultural Science", "Basic Science"],
    experience: 9,
    waecPassRate: 86,
    bio: "Jude teaches with an emphasis on environmental responsibility and sustainable farming.",
    cv: "/downloads/jude-ibe-cv.pdf",
  },
  {
    name: "Mrs. Ruth Ade",
    department: "Arts",
    subjects: ["Music", "Drama"],
    experience: 6,
    waecPassRate: 94,
    bio: "Ruth brings creative expression into the classroom, empowering students through performance arts.",
    cv: "/downloads/ruth-ade-cv.pdf",
  },
  {
    name: "Mr. Moses Danladi",
    department: "Commercial",
    subjects: ["Insurance", "Commerce"],
    experience: 8,
    waecPassRate: 88,
    bio: "Moses has a flair for breaking down complex financial topics into understandable lessons.",
    cv: "/downloads/moses-danladi-cv.pdf",
  },
  {
    name: "Miss Juliet Akinwale",
    department: "Science",
    subjects: ["Home Economics", "Basic Tech"],
    experience: 7,
    waecPassRate: 85,
    bio: "Juliet is passionate about applied sciences and equipping students with life skills.",
    cv: "/downloads/juliet-akinwale-cv.pdf",
  },
  {
    name: "Mr. Kingsley Obinna",
    department: "Arts",
    subjects: ["Visual Arts", "Design"],
    experience: 11,
    waecPassRate: 90,
    bio: "Kingsley encourages visual storytelling and inspires future designers through hands-on creativity.",
    cv: "/downloads/kingsley-obinna-cv.pdf",
  },
  {
    name: "Mrs. Ngozi Chukwuma",
    department: "Commercial",
    subjects: ["Data Processing", "Information Management"],
    experience: 10,
    waecPassRate: 89,
    bio: "Ngozi blends technology with business training, preparing students for today’s digital economy.",
    cv: "/downloads/ngozi-chukwuma-cv.pdf",
  },
];
